name: "Terraform-Infra-Apply-DevEnv"

on:
  push:
    branches:
      - dev
      - FeatureBranch1
  #pull_request:
    #branches:
      #- dev

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create symlink to modules directory
        run: ln -s ../modules ./dev/modules
        if: ${{ github.workspace }}/modules != './dev/modules'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./dev
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./dev 
      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve 
        working-directory: ./dev
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - name: Install Ansible,boto and store ssh key in runner
        run: |
           python -m pip install --upgrade pip
           pip3 install ansible
           pip3 install boto3
           mkdir -p /home/runner/.ssh/
           touch /home/runner/.ssh/config
           touch /home/runner/.ssh/id_rsa
           echo -e "${{ secrets.ANSIBLE_SSH_KEY }}" > /home/runner/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
      - name: Generate Ansible Dynamic Inventory
        run: |
          ansible-inventory -i ${{ github.workspace }}/dev/inventory/hosts.yaml --list -vvv
          ansible-inventory -i ${{ github.workspace }}/dev/inventory/hosts.yaml --graph -vvv
        working-directory: ./ansible_playbook
      - name: Deploy necessary applications to webservers with playbook
        run: |
           ansible-playbook -i ${{ github.workspace }}/dev/inventory/hosts.yaml -u ${{ secrets.webserver_user }} main.yml -vvv
        working-directory: ./ansible_playbook
          