name: "Terraform-Infra-Apply-dev_env"

on:
  push:
    branches:
      - dev
      - FeatureBranch1
  #pull_request:
    #branches:
      #- dev

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
       ENVIRONMENT: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Create symlink to modules directory
        run: ln -s ../modules ./$ENVIRONMENT/modules
        if: ${{ github.workspace }}/modules != './$ENVIRONMENT/modules'
      - name: Terraform Init
        id: init
        run: |
          cd ${{ github.workspace }}/$ENVIRONMENT  
          terraform init
        #working-directory: $ENVIRONMENT
      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ github.workspace }}/$ENVIRONMENT  
          terraform plan
        #working-directory: $ENVIRONMENT 
      - name: Terraform apply
        run: |
          cd ${{ github.workspace }}/$ENVIRONMENT  
          terraform apply --auto-approve
        #working-directory: $ENVIRONMENT

      - name: Create symlink to modules directory from shared directory
        run: ln -s ../modules ./shared/modules
        if: ${{ github.workspace }}/modules != './shared/modules'
      - name: Terraform Init
        id: shared_init
        run: terraform init
        working-directory: ./shared
      - name: Terraform Plan
        id: shared_plan
        run: terraform plan
        working-directory: ./shared
      - name: Terraform apply
        id: shared_apply
        run: terraform apply --auto-approve 
        working-directory: ./shared
     