name: "Terraform-Infra-Apply-StagingEnv"

on:
  push:
    branches:
      - staging
  #pull_request:
    #branches:
      #- staging

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create symlink to modules directory
        run: ln -s ../modules ./$ENVIRONMENT/modules
        if: ${{ github.workspace }}/modules != './$ENVIRONMENT/modules'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./$ENVIRONMENT
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./$ENVIRONMENT
      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./$ENVIRONMENT

